### ISSUE TITLE
GDPR Compliance, the easy way

### ISSUE THREAD

**Issue by NoSubstitute** [neochief/ReadingLine#1]
Hi, Alexander!

Would you mind clarifying on your github (and in Chrome Webstore) what your extension can, and can't do? Just like Linus Denison has done for his ruler. 
https://github.com/denisonlinus/reading-ruler#data-protection-faq

This will make it easier for schools to allow your extension now when we all have to be GDPR compliant.

Thank you in advance.

/Kim

**Comment by neochief** [comment]
That's ridiculous, but okay, I've updated everything.
